message: Welcome to wkim's house

---

spring:
  profiles: dev
  app: wkim's app

message: this is wkim's app DEV11112222223333

---

spring:
  profiles: stage
  app: wkim's app

message: this is wkim's app STAGE    