message: Welcome to wkim's house

---

spring:
  profiles: dev
  app: wkim's app

message: this is wkim's app DEV1111

---

spring:
  profiles: stage
  app: wkim's app

message: this is wkim's app STAGE    